# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: 
google_analytics: 
title: Ju4n S3rr4n0

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: dbyll

description: Loco por la productividad, linux y python
author:
  name: ju4nS3rr4n0
  email: ju4nS3rr4n0@gmail.com
  github: ju4nS3rr4n0
  twitter: ju4nS3rr4n0
  pinterest: 
  linkedin: 
  bio: Loco por la productividad, linux y python
  email_md5: 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
